# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meepachat < Formula
  desc "MeepaChat - Self-hosted team chat server (Go + React + Zitadel)"
  homepage "https://github.com/bogpad/meepa"
  version "0.4.42"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bogpad/meepachat/releases/download/v0.4.42/meepachat_0.4.42_darwin_amd64.tar.gz"
      sha256 "e194db1cb53f85edc9b3c372223688f97f408b238234a8a8022d97a893f1aa04"

      define_method(:install) do
        bin.install "meepachat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bogpad/meepachat/releases/download/v0.4.42/meepachat_0.4.42_darwin_arm64.tar.gz"
      sha256 "cd7dbaddef853be32880abe98e34f9649dfec91698a2cbc457d2fdd19b54a059"

      define_method(:install) do
        bin.install "meepachat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bogpad/meepachat/releases/download/v0.4.42/meepachat_0.4.42_linux_amd64.tar.gz"
      sha256 "4492c6b86d9a408be9cd611c3946a6be2ecc6d987e8badf064830b87b1d1906f"
      define_method(:install) do
        bin.install "meepachat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bogpad/meepachat/releases/download/v0.4.42/meepachat_0.4.42_linux_arm64.tar.gz"
      sha256 "5ca99539f8c10903423b9c685d434af52dc98a4e1680aa9f071a3b0e98f4dc5d"
      define_method(:install) do
        bin.install "meepachat"
      end
    end
  end
end
