# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meepachat < Formula
  desc "MeepaChat - Self-hosted team chat server"
  homepage "https://github.com/bogpad/meepachat"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bogpad/meepachat/releases/download/v0.0.5/meepachat_0.0.5_darwin_amd64.tar.gz"
      sha256 "8f00ea24e4b15575fdb29f745ceaa4b012a3778950c9be6c942afefddadfa468"

      define_method(:install) do
        bin.install "meepachat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bogpad/meepachat/releases/download/v0.0.5/meepachat_0.0.5_darwin_arm64.tar.gz"
      sha256 "d28dc849afd3a8f20eeca70db4de8a61ce3130f343fde0b76415be571de0b0bb"

      define_method(:install) do
        bin.install "meepachat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bogpad/meepachat/releases/download/v0.0.5/meepachat_0.0.5_linux_amd64.tar.gz"
      sha256 "791b7f232eb95aaaa53ea4843c04cebea07b070b5e2eed2e51c6b22026296e6b"
      define_method(:install) do
        bin.install "meepachat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bogpad/meepachat/releases/download/v0.0.5/meepachat_0.0.5_linux_arm64.tar.gz"
      sha256 "c0eaeb818cf60e1e21bf33ba196c24c2131f42ed951fa7ad859c2c51721dc637"
      define_method(:install) do
        bin.install "meepachat"
      end
    end
  end
end
