# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Meepachat < Formula
  desc "MeepaChat - Self-hosted team chat server (Go + React + Zitadel)"
  homepage "https://github.com/bogpad/meepa"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bogpad/homebrew-tap/releases/download/v0.1.8/meepachat_0.1.8_darwin_amd64.tar.gz"
      sha256 "5c78806fa473fc9330e8f920052e2cd0a511bb29d263c845f1c9cb40d522cfa9"

      def install
        bin.install "meepachat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bogpad/homebrew-tap/releases/download/v0.1.8/meepachat_0.1.8_darwin_arm64.tar.gz"
      sha256 "c6e47b9508dde1ef6d8fba7e13dbad15ced99ec564a4d821ce44195944f8a13a"

      def install
        bin.install "meepachat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bogpad/homebrew-tap/releases/download/v0.1.8/meepachat_0.1.8_linux_amd64.tar.gz"
      sha256 "2995367372e9e26baa80bb37d539abd67720087d9d5f6802325038a483ba32b1"
      def install
        bin.install "meepachat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bogpad/homebrew-tap/releases/download/v0.1.8/meepachat_0.1.8_linux_arm64.tar.gz"
      sha256 "185312428b40f1b65fb39196cba9c680585853cd19e43469ac7b56bafb35de8d"
      def install
        bin.install "meepachat"
      end
    end
  end
end
