# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MeepachatCli < Formula
  desc "MeepaChat CLI - Command-line client for MeepaChat"
  homepage "https://github.com/bogpad/meepachat"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bogpad/meepachat/releases/download/v0.0.6/meepachat-cli_0.0.6_darwin_amd64.tar.gz"
      sha256 "5ce0a087b418a4fbd01f1948329e132615362d504017340b83fe7bc485a2aa40"

      define_method(:install) do
        bin.install "meepachat-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bogpad/meepachat/releases/download/v0.0.6/meepachat-cli_0.0.6_darwin_arm64.tar.gz"
      sha256 "684ca8b5ba61e0e028d774365aa6a8642e3f4f8940c9bc2876776475b01ec89a"

      define_method(:install) do
        bin.install "meepachat-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bogpad/meepachat/releases/download/v0.0.6/meepachat-cli_0.0.6_linux_amd64.tar.gz"
      sha256 "7c3c26086fd792f96d7057f4bc37321fd0687ab3c788c4d14ae558d21f2624f4"
      define_method(:install) do
        bin.install "meepachat-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bogpad/meepachat/releases/download/v0.0.6/meepachat-cli_0.0.6_linux_arm64.tar.gz"
      sha256 "c9a6488aa4709c1997b2708847149a06d4a8509ae5ab12032ef129e4aa820c85"
      define_method(:install) do
        bin.install "meepachat-cli"
      end
    end
  end
end
